name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4
      - name: INSTALL DEPS
        run: npm ci
      - name: LINT
        run: npm run lint
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4
      - name: INSTALL DEPS
        run: npm ci
      - name: TEST
        run: npm run test
